name: Test chart

on:
  pull_request:
    paths:
      - 'helm/**'
      - 'Makefile.custom.mk'
      - '.github/workflows/test-chart.yaml'

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5
      - run: make test-chart
